repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
    -   id: black
-   repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.12
    hooks:
    -   id: shellcheck
-   repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.45.0
    hooks:
    -   id: terraform_fmt
    -   id: terraform_docs
    -   id: terraform_tflint
